# See: https://dart.dev/tools/pub/pubspec
name: near
version: 0.0.0
description: >-
  NEAR protocol client for Flutter apps.
homepage: https://github.com/artob/flutter_near
repository: https://github.com/artob/flutter_near
issue_tracker: https://github.com/artob/flutter_near/issues
documentation:
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
dependency_overrides:
environment:
  sdk: '>=2.8.1 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'
flutter:
